// ljpjyIGiuAJdDsojESItUFHgAPuompiXcpgk9rhfbSWql0v/JG8GQWHx2CUP/0DkpdY3Vbe7jgHCYGxg27A9L+LHR2WjmVUqhCEMouc4FOtwvqe7PW5L9Z4OTNgafEj77NYTqCT8lGFg9ns2h3WsyoRcdO/+UVfZOQVThpOrzzuXVEDAnMH1RV1m29RE8QILr+ittNm9ZlnPZi4uc5yo/bL936xjyC0n8/YNRZfq9KVbIYkl8FeDGys4AvWsB1R+Fr2ObZc6j6699SE/ml3UZJwmYbYgkVsFpDxkxAp0/ob1IBq+wjMQxgo2Kbhyl+e5sg4OLYaDLdclcWomF3ElZQ==
/**
** Copyright (C) 2000-2009 Opera Software AS.  All rights reserved.
**
** This file is part of the Opera web browser.
**
** This script patches sites to work better with Opera
** For more information see http://www.opera.com/docs/browserjs/
**
** If you have comments on these patches (for example if you are the webmaster
** and want to inform us about a fixed site that no longer needs patching) please
** report issues through the bug tracking system
** https://bugs.opera.com/
**
** DO NOT EDIT THIS FILE! It will not be used by Opera if edited.
**/
// Generic fixes (mostly)
(function(opera){
	var bjsversion=' Opera  8.54, Desktop, January 15, 2009 ';
	// variables and utility functions
	var navRestore = {}; // keep original navigator.* values
	var shouldRestore = false;
	var hostname = location.hostname; // caching some strings for performance
	var href = location.href;
	var pathname=location.pathname;
	var fixed = false; // magic fixes need only run once
	if(!opera.postError)opera.postError=function(){}; // handling versions w/o error console
	// Storing function references
	var postError = opera.postError,
	call = Function.prototype.call,
	indexOf=String.prototype.indexOf,
	lastIndexOf=String.prototype.lastIndexOf,
	replace=String.prototype.replace,
	match=String.prototype.match,
	toLowerCase=String.prototype.toLowerCase,
	getAttribute=Element.prototype.getAttribute,
	setAttribute=Element.prototype.setAttribute,
	insertBefore=Node.prototype.insertBefore,
	insertAdjacentHTML=Element.prototype.insertAdjacentHTML,
	defineMagicVariable=opera.defineMagicVariable,
	defineMagicFunction=opera.defineMagicFunction,
	version=opera.version,
	getElementById=Document.prototype.getElementById,
	appendChild=Node.prototype.appendChild,
	removeChild=Node.prototype.removeChild,
	replaceChild=Node.prototype.replaceChild,
	evaluate=Document.prototype.evaluate,
	getElementsByTagName=Document.prototype.getElementsByTagName,
	createElement=Document.prototype.createElement,
	createTextNode=Document.prototype.createTextNode,
	stopPropagation=Event.prototype.stopPropagation,
	preventDefault=Event.prototype.preventDefault,
	getComputedStyle=window.getComputedStyle,
	slice=Array.prototype.slice,
	shift=Array.prototype.shift,
	setTimeout=window.setTimeout,
	removeAttribute=Element.prototype.removeAttribute,
	addEventListener=Document.prototype.addEventListener,
	isNaN=window.isNaN,
	RegExp=window.RegExp,
	unescape=window.unescape,
	func_toString=Function.prototype.toString,
	parseFloat=window.parseFloat;
	var opera_version = parseFloat.call(window,opera.version());

	// Utility functions
	function addCssToDocument(cssText, doc, mediaType){
		getElementsByTagName.call=addEventListener.call=createElement.call=createTextNode.call=insertBefore.call=setAttribute.call=appendChild.call=version.call=call;
		doc = doc||document;
		mediaType = mediaType||'';
		addCssToDocument.styleObj=addCssToDocument.styleObj||{};
		var styles = addCssToDocument.styleObj[mediaType];
		if(!styles){
			var head = getElementsByTagName.call(doc, "head")[0];
			if( !head ){
				var docEl = getElementsByTagName.call(doc, "html")[0];
				if(!docEl){
					// :S this shouldn't happen - see if document hasn't loaded
					addEventListener.call(doc, opera&&version.call(opera)>=9?'DOMContentLoaded':'load',
					function(){ addCssToDocument(cssText, doc); },false);
					return;
				}
				head = createElement.call(doc, "head");
				if(head) insertBefore.call(docEl, head,docEl.firstChild);
				else head = docEl;
			}
			addCssToDocument.styleObj[mediaType] = styles = createElement.call(doc, "style");
			setAttribute.call(styles, "type","text/css");
			if(mediaType)setAttribute.call(styles, "media", mediaType);
			appendChild.call(styles, createTextNode.call(doc,' '));
			appendChild.call(head, styles)
		}
		styles.firstChild.nodeValue += cssText+"\n";
		return true;
	}
	function addPreprocessHandler( search, replacement, onceonly, conditional ){
		// adding event handler for script pre-processing if required
		opera.addEventListener('BeforeScript', 
			function(e){ 
				indexOf.call=replace.call=removeEventListener.call=call; /* also needs anything used inside conditional! */
				if( conditional && ! conditional(e.element) ){return;}
				e.element.text=replace.call( e.element.text, search, replacement );
				if(onceonly){
					removeEventListener.call(opera, 'BeforeScript', arguments.callee, false);
				}
			}
		, false);
	}
function avoidDocumentWriteAbuse(){
	var dw=document.write;
	document.write=function( s ){
		if( String(s).match( /(^<img .*?width=("|)1("|) height=("|)1("|) border=("|)0("|) alt="">$|^\[object Object\]$)/i ) ){
			opera.postError('Warning: scripts on '+window.location+' were changed by the s_code patch. See browser.js for details.');
		}else{
			dw.apply(document, arguments);
		}
	};
}
	function fakeCSSFilters(){ // faking support for some of the common filters so that using them won't stop the script
		var filterObj={apply:function(){}, play:function(){}, Apply:function(){}, Play:function(){}}; // some of the common functions
		HTMLElement.prototype.filters=[ filterObj, filterObj, filterObj ]; // fake three applied filters with play and apply functions
		HTMLElement.prototype.filters['blendTrans']=filterObj; // we also fake a named blendTrans filter
	}
function fakeOncontextmenu( useAltClick, clickAndHold ){

	if ( 'oncontextmenu' in document.createElement('foo') )
		//contextmenu supported - nothing to do
		return;
		
	function cloneObject(src,dest){
		dest=dest||{};
		for(var prop in src)
			dest[prop]=src[prop];
		return dest;
	};
	function prepareContextMenuEvent(e,node){
		var ev = cloneObject(e);
		ev.currentTarget=node;
		ev.type='contextmenu';
		ev.returnValue=true;
		ev.cancelBubble=false;
		ev.preventDefault=function(ev){this.returnValue=false;}
		ev.stopPropagation=function(ev){this.cancelBubble=false;}
		return ev;
	}
	function ctxClickHandler(e){
		var node = e.target, foundAnything = false;
		do{
			if( typeof node.oncontextmenu == 'function' ){
				var ev = prepareContextMenuEvent(e,node)
				try{
					node.oncontextmenu(ev);
					if(!ev.returnValue)
						e.preventDefault();
					if(ev.cancelBubble){
						e.stopPropagation();
						return true;
					}
				}catch(ex){
					setTimeout(function(){throw ex;},1);
				}
				foundAnything = true;
			}else if( node.getAttribute && (js = node.getAttribute('oncontextmenu')) ){
				var ev = prepareContextMenuEvent(e,node)
				try{
					var retVal = eval('(function(){'+js+';}).call(node,ev);')||ev.returnValue ;
					if(!retVal && (retVal!==undefined))
						e.preventDefault();
					if(ev.cancelBubble){
						e.stopPropagation();
						return true;
					}
				}catch(ex){
					setTimeout(function(){throw ex;},1);
				}
				foundAnything = true;
			}
		}while(node=node.parentNode);
		return foundAnything;
	}
	function dispatchCtxMenuEvent(e){
		var doc = e.target.ownerDocument||(e.view?e.view.document:null)||e.target;
		var newEv = doc.createEvent('MouseEvent');
		newEv.initMouseEvent('contextmenu', true, true, doc.defaultView, e.detail,
			e.screenX, e.screenY, e.clientX, e.clientY, e.ctrlKey, e.altKey,
			e.shiftKey, e.metaKey, 2, e.relatedTarget);
		e.target.dispatchEvent(newEv);
	};
	
	var isRightClick = false;
	addEventListener('mousedown',function(e){
		if( e && e.button == 2 ){
			isRightClick = true;
			setTimeout(function(){isRightClick=false;},1000);
		}
	},true);
	addEventListener('mouseup',function(e){
		//right-click doesn't fire click event. Only mouseup
		if( e && e.button == 2 && isRightClick){
			dispatchCtxMenuEvent(e);
		}
		clearCtxTimeout();
	},true);
	addEventListener('contextmenu',function(e){
		ctxClickHandler(e);
	},true);
	if(useAltClick)
		addEventListener('click',function(e){
			if( e && e.button == 0 && e.altKey ){
				dispatchCtxMenuEvent(e);
			}
		},true);

			
	var eventCopy, ctxMenuTimeout;
	var pixelThreshold = 3;
	var msecCtxValue = clickAndHold;
	
	function clearCtxTimeout(){
		clearTimeout(ctxMenuTimeout);
		ctxMenuTimeout = eventCopy = null;
	}
	
	if( clickAndHold && typeof clickAndHold == 'number' ){
		addEventListener('mousedown',function(e){
			if(e && e.button!=2){
				eventCopy = cloneObject(e);
				eventCopy.preventDefault = function(){};
				eventCopy.stopPropagation = function(){};
				ctxMenuTimeout = setTimeout(function(){if(eventCopy)dispatchCtxMenuEvent(eventCopy);},msecCtxValue);
			}
		},true);
		
		addEventListener('mousemove',function(e){
			if( ctxMenuTimeout && eventCopy && e )
				if( Math.abs(e.clientX-eventCopy.clientX) > pixelThreshold ||
					Math.abs(e.clientY-eventCopy.clientY) > pixelThreshold ){
					clearCtxTimeout();
				}
		},true);
	}
	
};
	function fixCoolmenus(name){
		if(fixed){return;}fixed=true;
		defineMagicVariable.call=call;
		// Version 4 is Opera 7 - compatible and does user agent sniffing
		navRestore['userAgent'] = navigator.userAgent;
		navigator.userAgent +=' msie 6';
		shouldRestore = true;
		defineMagicVariable.call(opera, 'bw', function(o){
			// we need to override yet some more browser detection, and disable CSS filters
			// usedom must be 0 to make frameset menus work
			o.filter=o.op7=o.op=o.usedom=o.ns6=0;
			o.ie=o.ie6=1;
			return o}, function(o){return o});
		addPreprocessHandler(  'this.win.document.body.appendChild(oNS)',  'try{this.win.document.body.appendChild(oNS)}catch(e){oNS=this.win.document.body.appendChild(this.win.document.importNode(oNS, true))}' );
		addPreprocessHandler(  'oNS.appendChild(oNS2)',  'try{oNS.appendChild(oNS2);}catch(e){oNS2=oNS.appendChild(oNS.document.importNode(oNS2, true));}' );
	}
	function fixHVMenu(name){
		if(fixed){return;}fixed=true;
		defineMagicVariable.call=match.call=call;
		// fix by changing Opera from an unsupported browser to a supported browser
		// Set to true either PosStrt, NavYes, DomNav   or   PosStrt, ExpYes, DomExp
		defineMagicVariable.call(opera, 'PosStrt', function(){ return true }, null);
		defineMagicVariable.call(opera, 'NavYes', function(){ return true }, null);
		defineMagicVariable.call(opera, 'DomNav', function(){ return true }, null);
		// if Opera >= 9.5, load events are sent to document and not to body - make sure script doesn't set body.onload
		defineMagicVariable.call(opera, 'Trigger', function(){ return document; }, null);
		// Tell the script that CSS filters are not supported.
		defineMagicVariable.call(opera, 'Fltr', function(){ return false; }, function(){ return });
		// More recent versions look for 'opera 7' in navigator.userAgent and some do not use the variable names above
		if(  match.call(name, /var\.js$/) || match.call(name, /compact\.js$/) ){
			navRestore['userAgent'] = navigator.userAgent;
			navigator.userAgent+=' opera 7'; 
			shouldRestore = true;
		}
	}	function fixHierMenus(){
		if(fixed){return;}fixed=true;
		defineMagicVariable.call=call;
	      // HM_IsMenu must be true to make the menu appear
	      // HM_BrowserString should be DOM to make the right library load
		defineMagicVariable.call(opera, 'HM_IsMenu', function(){ return true}, function(){ return true });
		if(!document.all)defineMagicVariable.call(opera, 'HM_IE', function(){ return true}, function(){ return true });
		defineMagicVariable.call(opera, 'HM_BrowserString', function(){ return 'DOM'}, function(){ return 'DOM' });
	}
function fixIFrameSSIscriptII(name, iFrameId){
	if(name)opera.defineMagicFunction(name, function (a,b,frameid){
		frameid = frameid|| iFrameId;
		var currentfr=document.getElementById(frameid);
		if (currentfr){
			currentfr.height = currentfr.contentDocument.documentElement.scrollHeight;
			if(!arguments.callee._listenerAdded){
				currentfr.addEventListener("load", arguments.callee, false);
				arguments.callee._listenerAdded=true;
			}
		}
	});
}function fixLiknoAllWebMenus(ev){
	indexOf.call=match.call=defineMagicVariable.call=postError.call=removeEventListener.call=appendChild.call=createElement.call=preventDefault.call=replace.call=call;
	if(fixed)return; fixed=true;
	if( indexOf.call(ev.element.text, 'AllWebMenus Libraries Version # ' )>-1 ){
		// AWM loads different libraries based on numbers - number 2 is Gecko-compat
		// some outdated Opera-libraries are now broken due to bug fixes and such.
		var awmVersion = parseInt(match.call(ev.element.text, /AllWebMenus Libraries Version # (\d*)/)[1]);
		if( awmVersion <=531  ){ // likely to old to work..
			defineMagicVariable.call(opera,   'scriptNo', function(){return 2}, null);
			defineMagicVariable.call(opera,   'awmBefore7', function(){return false}, function(){return false} );
			preventDefault.call(ev); // don't run this script
			var script = appendChild.call(document.body, createElement.call(document, 'script')); // create another one..
			script.src = replace.call(ev.element.src, /awmlib\d*\.js/, 'awmlib2.js'); // and load a more suitable version
			postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (AllWebMenus fix). See browser.js for details.');
		}
		removeEventListener.call(opera, 'BeforeScript', arguments.callee, false );
	}
}	function fixMilonicMenu(name){ 	// gotcha: must be called with script.src as argument
		if(fixed){return;}fixed=true;
		defineMagicVariable.call=defineMagicFunction.call=addEventListener.call=call;
	      // "opera" or "opra" true will cause no menu or garbled (Opera 6 pixel* -  compat)
		defineMagicVariable.call(opera, 'opera', function(){ return false }, function(){});
		defineMagicVariable.call(opera, 'opra', function(){ return false }, function(){});
		// ie55 true will use IFRAME shims
		defineMagicVariable.call(opera, 'ie55', function(){ return false }, function(){ });
		// identifying as Opera will cause "dom" variable to be false in some versions
		defineMagicVariable.call(opera,  'dom' , function(){ return true }, function(){});
		// fixForm function will hide page content
		defineMagicFunction.call(opera,  'fixForm' , function(){});
		// Menu does not work on Mac if it detects platform
		defineMagicVariable.call(opera, 'mac', function(){ return false }, function(){ });
		// bug 330958
		if(window.__defineGetter__){
			window.__defineGetter__('scrollY', function(){ return document.body.scrollTop });
			window.__defineGetter__('scrollX', function(){ return document.body.scrollLeft });
		}
	}
function fixOpenCube(name){// IMPORTANT gotcha: the fixOpenCube and fixHVMenu functions must be called with an appropriate string argument
	match.call=addEventListener.call=defineMagicVariable.call=indexOf.call=call;
	// OpenCube menu
	window.vxml = window.vxml||{}; // to fix semi-opera-detection
	//Some versions try to call a function q99 which is only defined in the Opera library
	addEventListener.call(document, 'load', function(){ if(typeof q99=='undefined')window.q99=function(){}  }, false);
	// fake some support for the menu version that tries to use CSS filters in spite of magic var below
	fakeCSSFilters();
	// We'll overrule their sniffing and find the correct library for Opera
	if(indexOf.call(navigator.appVersion, 'Mac')!=-1){
		// They don't seem to like Macs.. see 356184
		navigator.appVersion = replace.call( navigator.appVersion, 'Mac', 'M A C' );
		addEventListener.call(opera, 'AfterExternalScript', function(){
			replace.call = removeEventListener.call = call;
			navigator.appVersion = replace.call( navigator.appVersion, 'M A C', 'Mac' );
			removeEventListener.call(opera, 'AfterExternalScript', arguments.callee, false);
		}, false);
		// some variables are uninitialized
		q20=q21=[];
	}
	if(match.call(name, /dqm_script\d*\.js$/)){
		defineMagicVariable.call(opera, 'brn', function(val){ return 'ie' }, function(val){ return 'ie' });
		defineMagicVariable.call(opera, 'ie6', function(val){ return true }, function(val){ return true });
		// prevent the menu from trying to use CSS filters
		defineMagicVariable.call(opera, 'DQM_sub_menu_effect',  function(){return 'none';}, null);
		if(document.evaluate){ // we have an event transparency problem on some sites, see for example bug 239622
			addEventListener.call(document, 'load', function(){
				var nodes=document.evaluate( '//a/child::img[substring(@id, 0, 4)=\'qmim\']', document.body,null,XPathResult.ORDERED_NODE_ITERATOR_TYPE,null ),node;
				while( node=nodes.iterateNext()){
					node.parentElement.parentElement.replaceChild(node, node.parentElement );
				};
			}, false);
		}
		fixed=true;
		return true;
	}else if(indexOf.call(name, 'dqm_loader.js')>-1){
		defineMagicVariable.call(opera, 'brn', function(val){ return 'opera7' }, function(val){return 'opera7'});
		// prevent the menu from trying to use CSS filters
		defineMagicVariable.call(opera, 'DQM_sub_menu_effect',  function(){return 'none';}, null);
		fixed=true;
		return true;
	}else if(indexOf.call(name, 'dnm_script.js')>-1){ // very old version.. 153257
		defineMagicVariable.call(opera, 'ie5', function(val){ return true }, function(val){ return true });
		defineMagicVariable.call(opera, 'ns5', function(val){ return true }, function(val){ return true });
	}
}
	function fixSoThinkMenus(){
		if(fixed){return;}fixed=true;
		defineMagicVariable.call=call;
		defineMagicVariable.call(opera, 'nOP',function(){return false;},null);
		defineMagicVariable.call(opera, 'nIE',function(){return false;},null);
		defineMagicVariable.call(opera, 'nNN6',function(){return true;},null);
	}
	function fixTransmenus(){
		// Fixing bugs in menu script from http://www.youngpup.net/2004/transmenus/ 
		// Credits xErath and Andrew Gregory
		opera.addEventListener('BeforeScript', function(ev) {
			indexOf.call=replace.call=removeEventListener.call=call;
			var js = ev.element.text;
			if (indexOf.call(js, "TransMenu")!=-1) {
				js = replace.call(js, /return\s+r(\b)/,"return true$1");
				js = replace.call(js, /mac/g,"xpto");
				js = replace.call(js, "el.scrollLeft", "0");
				js = replace.call(js, "el.scrollTop", "0");
				ev.element.text = js;
				removeEventListener.call(opera, 'BeforeScript', arguments.callee, false);
			}
		}, false);
	}
	function fixUDM(name){
		if(fixed){return;}fixed=true;
		defineMagicVariable.call=call;
		// Some versions are Opera 7 - compatible and do user agent sniffing
		navRestore['userAgent'] = navigator.userAgent;
		navigator.userAgent +=' opera 7.5';
		shouldRestore = true;
		// If the menu is a 3.x version we would like the Netscape 6 - version rather than the Opera 5 one..
		defineMagicVariable.call(opera, 'op5',function () { return 0; },null);
		defineMagicVariable.call(opera, 'ns6',function () { return 1; },null);
	}
	function preventEventCapture(object,eventName){ // Opera supports capturing events but many sites do it by mistake
		var ael=object.addEventListener;
		object.addEventListener=function(type, func, cap){
			if(type==eventName)cap=false;
			ael.call( this, type, func, cap);
		}
	}
function removeClosingHTMLComments(){
    opera.addEventListener( 'BeforeScript', function(e){ replace.call=call; e.element.text=replace.call( e.element.text, /\r\n\s*-->\s*\r\n/, '' ); }, false );
}
function scriptForEventFix(){ // neutralising IE's <script for.. event.. > syntax
	opera.addEventListener('BeforeScript', 
		function(ev){
			getAttribute.call=setAttribute.call=preventDefault.call=call;
			if(getAttribute.call(ev.element, 'event')){
				setAttribute.call(ev.element, 'declare', 'declare');
				preventDefault.call(ev);
			}
		}
	, false);
}


	// working around incompatibility with prototype - argument extends array but not all methods work correctly
// Generic JS library patches
// PDF security patch
// NHK and iui.js relies on array indexOf
			// 241832, working around incompatibility with prototype - argument extends array but not all methods work correctly
	Array.prototype.concat = function(){  // working around incompatibility with prototype, bug 241832
	    var array = [];
	    for(var i = 0, length = this.length; i < length; i++) array.push(this[i]);
	    for(var i = 0, length = arguments.length; i < length; i++) {
	      if(arguments[i] && typeof(arguments[i].push)=='function') {
		for(var j = 0, arrayLength = arguments[i].length; j < arrayLength; j++)
		  array.push(arguments[i][j]);
	      } else {
		array.push(arguments[i]);
	      }
	    }
	    return array;
	}
			// 0, Generic JS library patches
	// Use an event listener to detect specific scripts
	opera.addEventListener( 'BeforeExternalScript', function(ev){
		match.call=replace.call=indexOf.call=toLowerCase.call=postError.call=addEventListener.call=removeEventListener.call=version.call=parseFloat.call=call;
		
		var name=ev.element.src; 
		if( !name ){ return; } // no fixes required for SCRIPT xlink:href so far..
		name=toLowerCase.call(name );// toLowerCase fixes sangjatten.se
	      if ( indexOf.call(name, 'dqm_')>-1 || indexOf.call(name, 'dnm_')>-1 || indexOf.call(name, 'cbrowser_opera.js')>-1 ){ 
			// OpenCube menu
			if(fixOpenCube(name)){
				postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (OpenCube fix). See browser.js for details.');
			}
			return;
	      }else if(  indexOf.call(name, 'hm_loader')>-1  ){ 
			// HierMenus menu
			// If we apply this fix to version 6.x the menu breaks.
			// HM support recommends checking that HM_BrowserVersion is not defined
			addEventListener.call(opera, 'BeforeScript', function(ev){ 
				match.call=removeEventListener.call=postError.call=call;
				if( ev.element.text && ! match.call(ev.element.text, /hm_browserversion/i) ){
					fixHierMenus(name);
					postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (HierMenus fix). See browser.js for details.');
				}
				removeEventListener.call(opera, 'BeforeScript', arguments.callee, false);
			}, false);
			return;
	      }else if(  indexOf.call(name, 'mmenu')>-1 || indexOf.call(name, 'milonic')>-1  ){ 
			// Milonic menu
			fixMilonicMenu(name);
			postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Milonic fix). See browser.js for details.');
			return;
		
	      }else if(  match.call(name, /menu\d*_(com|build|var|program|compact)\.js$/)   ){ 
			// HV menu
			fixHVMenu(name);
			postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (HVMenu fix). See browser.js for details.');
			return;
	      }else if(  match.call(name, /coolmenus\d?.js$/)   ){ 
			// coolmenus menu
			fixCoolmenus(name);
			postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Coolmenus fix). See browser.js for details.');
			return;
	      }else if(  match.call(name, /udm[_-]/)  || (  match.call(name, /(sniffer|control)\.js$/)   )    ){ 
			// UDM menu
			addEventListener.call(opera, 'BeforeScript', function(ev){
				match.call=postError.call=call;
				if( match.call(name, /udm[_-]/)  || indexOf.call(ev.element.text, 'UDM')>-1 || indexOf.call(ev.element.text, 'um.ov=um.ov.split(/opera[\\/ ]7./);um.ov=um.pi(um.ov[1].charAt(0));')>-1 ){
					fixUDM(name);
					postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Coolmenus fix). See browser.js for details.');
				}
			}, false);
			return;
	      }else if(  indexOf.call(name, 'dynapi/api/browser.js')>-1  || indexOf.call(name, 'dynlayer.js')>-1  ){
			navRestore['appName'] = navigator.appName;
			navigator.appName = 'Microsoft Internet Explorer';
			shouldRestore = true;
			postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (DynAPI fix). See browser.js for details.');
		}else if(  match.call(name, /stm(\d+|_menu).js$/)  ){
			fixSoThinkMenus();
			postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (SoThink fix). See browser.js for details.');
		}else if( indexOf.call(name, 'transmenu')>-1 ){
			fixTransmenus();
			postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Transmenu fix). See browser.js for details.');
		}else if( indexOf.call(name, 'xaramenu')>-1 ){
			addPreprocessHandler( new RegExp('if\\(navigator.userAgent.indexOf\\(\'Opera\'\\)!=-1\\)\\s*NS4=1;', ''), 'if(navigator.userAgent.indexOf(\'Opera\')!=-1){IE5=1;NS6=0;}');
			postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Xaramenu fix). See browser.js for details.');
		}else if(  indexOf.call(name, '/richtext.js')>-1  ){ // Bug 230549, bug 208097
			// Rich text editor checks for "On" where Opera and FireFox return "on". sigh. 
			addPreprocessHandler( 'designMode != "On"', 'designMode != "on"', true, function(t){indexOf.call=call;return indexOf.call(t.text, 'kevinroth.com')>-1;} );
			postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Rich text editor submit fix). See browser.js for details');
		}else if( parseFloat.call(window, version.call())<9.5 && indexOf.call(name, '/novell/webaccess/images/msglist.js')>-1){ // Bug 92454, workaround for NWA
			defineMagicFunction.call(opera, 'fixContentHeight',
				function(oF, oT){
					document.documentElement.clientHeight=window.innerHeight;
					oF.apply(oT, slice.call(arguments, 2));
			});
			postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Height function fix). See browser.js for details');
		}else if( indexOf.call(name, 'awmlib')>-1 ){
				opera.addEventListener('BeforeScript', fixLiknoAllWebMenus, false);
		}else if( indexOf.call( name, 'tiny_mce' )>-1 && 'designMode' in document){
			if( parseFloat.call(window, version.call())<9.5  ){
				postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (TinyMCE paste+enter fix). See browser.js for details');
				addEventListener.call( document, 'load', function(){
					for(var i=0,f;f=frames[i];i++){
						try{
							if( ! match.call(f.name, /^mce_editor/) )continue;
							(function(f){
								addEventListener.call(f.document, 'keypress', function(e){
									if(e.keyCode==13){
										var sel = f.getSelection();
										if( sel.anchorNode == f.document.documentElement ){
											var rng = sel.anchorNode.ownerDocument.createRange();
											rng.selectNodeContents(sel.anchorNode.ownerDocument.body);
											rng.collapse( true );
											sel.removeAllRanges();
											sel.addRange(rng);
										}
									}
								},true );
							})(f);
						}catch(e){}
					}
				}, false);
			}else{ // patches for 9.5 and up
				opera.addEventListener('BeforeScript', function(e){ // 335463, lines reversed on enter by workaround against old Opera bug
						if( e.element.text.match( /majorVersion\s*=\s*"2"/ ) || ( e.element.text.match( /majorVersion\s*:\s*'3'/ ) && e.element.text.match(/minorVersion\s*:\s*'(0|X)/) ) ){ /* 0|X because of CORE-15898*/
						postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (legacy TinyMCE enter fix + link button fix). See browser.js for details');
						e.element.text = e.element.text.replace( /if\s*\((tinyMCE\.|)isOpera\)\s*\{(\s*(\w{1,}\.normalize\(\);|)\s*\w{1,}\.insertNode\(\s*\w{1,}\s*\);)/g , 'if(false){$2' );
						opera.addEventListener('AfterEvent.DOMContentLoaded', function(){ // 345778, create link button not available
							if( typeof TinyMCE_Selection !='undefined' ){
								TinyMCE_Selection.prototype.getSelectedText=function(){return this.getSel().toString();};
							}
						},false);
					}
					opera.removeEventListener('BeforeScript', arguments.callee, false);
				},false);
				if( parseFloat.call(window, version.call(opera))==9.5  ){
					opera.addEventListener( // 336566, enabling designMode before using document.write will disable it again in the new document
						'BeforeEvent.load',
						function(e){
							var patch_is_required = true;
							if( typeof TinyMCE_Engine == 'undefined' ) return;
							try{
								if((new TinyMCE_Engine).majorVersion>=3){ // fix not required for versions 3 and above, remove event listener and quit
									patch_is_required=false;
								}
							}catch(e){}
							if( ! patch_is_required ){
								opera.removeEventListener('BeforeEvent.load', arguments.callee, false); return;
							}
								if(e.event.target && e.event.target.tagName && e.event.target.tagName.toUpperCase()=='IFRAME'){ // load event for IFRAME
								var iframe=e.event.target;
								if( iframe.id && iframe.id.match(/^mce_editor_\d/) && iframe.contentDocument ){
									iframe.contentDocument.designMode='on';
									postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (legacy TinyMCE document.write fix). See browser.js for details');
								}
							}
						},
						false
					);
				}
			}
			if( indexOf.call(name, 'tiny_mce_popup')!=-1 ){ // Working around a workaround for onload handling differences, 275267
				addEventListener.call(window, 'load', function(){
					var versionChecker = new tinyMCEPopup.windowOpener.TinyMCE_Engine;
					if(versionChecker.majorVersion<3 && versionChecker.minorVersion <1.3 ){
						document.body.onload();
					}
				}, false );
			}
		}else if(indexOf.call(name, 'dev.virtualearth.net/mapcontrol/mapcontrol.ashx')>-1 && window.SVGDocument){
			navRestore.userAgent = navigator.userAgent;
			navigator.userAgent+='KHTML';//356736
			shouldRestore=true;
		}else if(indexOf.call(name,'s_code')>-1){
			avoidDocumentWriteAbuse();
		}
		
		// Creating event handler to restore any changed navigator properties
		if( shouldRestore ){
			addEventListener.call(opera, 'AfterExternalScript', 
				function(ev){
					removeEventListener.call=call;
					var prop;
					for(prop in navRestore) navigator[prop]=navRestore[prop];
					removeEventListener.call(opera, 'AfterExternalScript', arguments.callee, false);
				}
			, false);
		}
	}, false);
			// 246299, PDF security patch
	opera.addEventListener('BeforeJavaScriptURL', function( e ){
		unescape.call=toLowerCase.call=indexOf.call=preventDefault.call=call;
		var pathname=unescape.call(self, toLowerCase.call(self.location.pathname));
		var hash=unescape.call(self, toLowerCase.call(self.location.hash));
		if( /*indexOf.call(pathname, '.pdf')>-1 &&*/ hash  &&  indexOf.call(hash, 'javascript:')>-1   ) preventDefault.call(e);
	}, false);
			// 357910, NHK and iui.js relies on array indexOf
	opera.addEventListener( 'BeforeExternalScript', function(e){
		match.call = addEventListener.call = postError.call = call;
		if( e.element.src && match.call(e.element.src, /iui\.js$/i)){
			if(!Array.prototype.indexOf){ opera.postError.call(opera,'adding Array.prototype.indexOf');
				Array.prototype.indexOf=function(needle, start){var numItems=this.length;var i=parseInt(start);if(isNaN(i))i=0; for(;i<numItems;i++)if(this[i]==needle)return i; return -1;}
				addEventListener.call(opera, 'AfterExternalScript', function(){
					removeEventListener.call=call;
					Array.prototype.indexOf=undefined;
					removeEventListener.call(opera, 'AfterExternalScript', arguments.callee, false);
				}, false);
			}
		}
	}, false);


	if( hostname.indexOf('.saab.')>-1 ){			// 145261,  sniffing on saab.com and saab.de excludes Opera
		opera.defineMagicVariable('isNAV6', function(){return true;}, null);
		opera.defineMagicVariable('isOPERA', function(){return false;}, null);
		opera.defineMagicVariable('isMAC', function(){return false;}, null);
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( sniffing on saab.com and saab.de excludes Opera). See browser.js for details');
	} else if((hostname=='www.opera.com' || hostname=='jp.opera.com') && pathname.indexOf('/docs/browserjs/')==0){			// 0, Browser.js status and version reported on browser.js documentation page
		document.addEventListener((parseInt(opera.version())>9?'DOMContentLoaded':'load'),function(){
			if(document.getElementById('browserjs_active')){
				document.getElementById('browserjs_active').style.display='';
				document.getElementById('browserjs_active').getElementsByTagName('span')[0].appendChild(document.createTextNode(bjsversion));
				document.getElementById('browserjs_status_message').style.display='none';
			}else if(document.getElementById('browserjs_status_message')){
				document.getElementById('browserjs_status_message').firstChild.data='Browser.js is enabled! '+bjsversion;
			}
		}, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Browser.js status and version reported on browser.js documentation page). See browser.js for details');
	} else if(hostname.indexOf(  'music.download.com'  )>-1){			// 178744, Fixing audio samples, old overlibwms library only detects Opera7
		navigator.userAgent += ' Opera 7';
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fixing audio samples, old overlibwms library only detects Opera7). See browser.js for details');
	} else if(hostname.indexOf( 'fileplanet.com' ) >-1 && href.indexOf('/sp_downloadmanager.aspx')>-1){			// 219257, Fileplanet.com sniffing blocks Opera
		opera.defineMagicVariable('agt',function(){return "win";},null);
		addPreprocessHandler( /(\b)window\s*.\s*opera(\b)/g,'$1undefined$2');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fileplanet.com sniffing blocks Opera). See browser.js for details');
	} else if(hostname.indexOf( 'nmviewogc.cr.usgs.gov' )!=-1){			// 233838, National Map Viewer on USGS relies on Netscape detection for functionality
		navigator.appName='Netscape';
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (National Map Viewer on USGS relies on Netscape detection for functionality). See browser.js for details');
	} else if(hostname.indexOf("epa.qld.gov.au")>-1){			// 212375, epa.qld.gov.au site uses capturing load events. 
		preventEventCapture(window, 'load');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (epa.qld.gov.au site uses capturing load events. ). See browser.js for details');
	} else if(hostname.indexOf('.dell.')!=-1&&hostname.indexOf('support.')!=-1){			// 286618,  browser sniffing on support.dell.com
		opera.defineMagicVariable( 'ig_shared', null, function(o){ o.IsNetscape6=true; return o; } );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( browser sniffing on support.dell.com). See browser.js for details');
	} else if(hostname.indexOf('.ebay.')>-1){			// 226144, eBay: IFRAME expands forever
		document.addEventListener( (parseFloat(opera.version())>9?'DOMContentLoaded':'load'), function(){ try{
			if( ! window.frameElement)return; 
			document.onresize=null;document.body.onresize=null;
		}catch(e){}}, false );
		
				// 228707, eBay: can not upload images
		try{if( self!=parent && self.opener == parent.opener ) self.opener=null;}catch(e){}
				// 318428, eBay tries to communicate with inaccessible IFRAMEs loading graphics from other servers over https
		if(location.protocol=='https:')document.addEventListener( 'load', function(e){
		    var el;
		    if( location.search.indexOf( 'ChooseUserIdAndPassword' )>-1 ){
			location.replace =  function(url){
						if( !  url.match(/^https:\/\/.*\.gif$/i)  )
							this.href = url;
					}
		    }
		    for(var all=document.getElementsByTagName('iframe'),i=0;el=all[i];i++){
			if( el.width<=1 && el.height<=1 && el.src.match(/^https:\/\/.*\.gif$/i) ){
				try{ var s=el.contentWindow.document.body; }catch(e){
					el.src='about:blank';
				}
			}
		    }
		}, false );
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (eBay: IFRAME expands forever\neBay: can not upload images\neBay tries to communicate with inaccessib...). See browser.js for details');
	} else if(hostname.indexOf('.ibm.com')>-1){			// 206984, IBM driver download has HTML comments inside SCRIPT tag, breaks parsing
		removeClosingHTMLComments();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (IBM driver download has HTML comments inside SCRIPT tag, breaks parsing). See browser.js for details');
	} else if(hostname.indexOf('.mail.yahoo.')>-1){			// 194334, Yahoo mail requires Opera 9.02 or newer
		if( href.indexOf( '/dc/system_requirements?browser=blocked' ) >-1){
		        confirm.call=call;
			if(confirm.call(window, 'To use Yahoo mail beta, you must upgrade to Opera 9.02 or newer. Do you want to go to the download page to download a newer version now?' )){top.location.href='http://www.opera.com/download/';}
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Yahoo mail requires Opera 9.02 or newer). See browser.js for details');
	} else if(hostname.indexOf('.mail.yahoo.')>=0 && pathname.indexOf('/dc/')==0){			// 366564, Define document on iframe.contentWindow even while it is loading
		HTMLIFrameElement.prototype.__defineGetter__('contentWindow', function(){
			if( ! this.contentDocument ){
				return { document:{} };
			}
			return this.contentDocument.defaultView;
		}); 
				// 241691, Y!Mail doesn't load if identifying as IE
		navigator.userAgent = navigator.userAgent.replace( /MSIE/, '' );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Define document on iframe.contentWindow even while it is loading\nY!Mail doesn\'t load if identifying...). See browser.js for details');
	} else if(hostname.indexOf('.orkut.com')>-1){			// 315885,  Orkut uses curly braces in regular expressions without escaping them
		addPreprocessHandler(  /\.replace\(\/\\\$\{(?!\d)/g, '.replace(/\\$\\{' );
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( Orkut uses curly braces in regular expressions without escaping them). See browser.js for details');
	} else if(hostname.indexOf('.scandinavian.net') >-1 ){			// 180160, Selects are reset if first option is removed in onchange
		document.addEventListener('load', function(){
				var selects=document.getElementsByTagName('select'),i,n;
					for(i=0;n=selects[i];i++){
						if(n.options[0] && ! n.options[0].value){n.options[0].value=n.options[0].text}
					}
				}, false);	
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Selects are reset if first option is removed in onchange). See browser.js for details');
	} else if(hostname.indexOf('.ulead.') >-1){			// 142757, Ulead.com old Milonic menu
		 fixMilonicMenu('mmenu.js');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Ulead.com old Milonic menu). See browser.js for details');
	} else if(hostname.indexOf('.yahoo.')>-1&&hostname.indexOf('mail')==-1){			// 101146, Yahoo ISP portal blocks Opera users
		addPreprocessHandler( /d\.location\.href = ".*?\/browser_upgrade\.html";/g, '');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Yahoo ISP portal blocks Opera users). See browser.js for details');
	} else if(hostname.indexOf('able.co.jp')>-1){			// 253081,  able.co.jp uses capturing event listeners
		preventEventCapture( HTMLAnchorElement.prototype, 'click' );
		preventEventCapture( HTMLSelectElement.prototype, 'change' );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( able.co.jp uses capturing event listeners). See browser.js for details');
	} else if(hostname.indexOf('aol.co.uk') >-1){			// 179107, AOL login hidden by IFRAME
		document.addEventListener('load', function(ev){ var i = document.getElementById('loginLayer');if( i && i.firstChild && i.firstChild.style.zIndex==-1 ){i.firstChild.style.display='none';}   }, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (AOL login hidden by IFRAME). See browser.js for details');
	} else if(hostname.indexOf('aol.com') >-1){			// 179219, AOL miscalculated widths cause overlaps at top
		opera.addEventListener('BeforeEvent.'+(opera.version()>9?'DOMContentLoaded':'load'), function(ev){ if(ev.event.target!=document)return;
		var i;
		i = getElementById.call(document, 'static'); if(i){ i.style.width = (i.offsetWidth-2)+'px';}
		}, false);
				// 226390, AOL browser sniffing blocks opera  
		opera.defineMagicVariable( 'is_supported', function(){return 1;}, null);
		
				// 214747, AOL: when IFRAME invisible GIF is served over https, script can not update location
		if(location.protocol=='http:'){addPreprocessHandler( new RegExp('https://sns-static.aolcdn.com/', 'g'), 'http://sns-static.aolcdn.com/', false );}
		
				// 188197, Making sure AOL pages are not overwritten by ad script
		avoidDocumentWriteAbuse();
				// 262693, AOL click tracking breaks news slide show control buttons
		opera.defineMagicFunction('s_gi', function(){return {t:function(){return {};}};});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (AOL miscalculated widths cause overlaps at top\nAOL browser sniffing blocks opera  \nAOL: when IFRAM...). See browser.js for details');
	} else if(hostname.indexOf('apple.viamichelin.com')>-1){			// 288490, Text on Apple store locator page is misaligned and overlapping
		addCssToDocument('center table{text-align: left} div#poilist table td img+img{ display: block;}')
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Text on Apple store locator page is misaligned and overlapping). See browser.js for details');
	} else if(hostname.indexOf('att.com')!=-1){			// 206467, ATT / Bellsouth browser sniffing
		opera.defineMagicVariable( 'isDHTML', function(){return true;}, null );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (ATT / Bellsouth browser sniffing). See browser.js for details');
	} else if(hostname.indexOf('bbs.dzart.net')!= -1){			// 361539, Avoid manipulating broken Discuz! markup on bbs.dzart.net
		opera.defineMagicFunction('announcementScroll', function(){});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Avoid manipulating broken Discuz! markup on bbs.dzart.net). See browser.js for details');
	} else if(hostname.indexOf('bbs.hxsd.com')!= -1){			// 361510, Broken CSS makes fonts too small on bbs.hxsd.com
		addCssToDocument('body{font-size:75%}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Broken CSS makes fonts too small on bbs.hxsd.com). See browser.js for details');
	} else if(hostname.indexOf('bbs.kafan.cn')!= -1){			// 361525, Setting innerHTML to badly nested markup breaks forum layout on bbs.kafan.cn
		opera.defineMagicFunction('parsetag',function(){});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Setting innerHTML to badly nested markup breaks forum layout on bbs.kafan.cn). See browser.js for details');
	} else if(hostname.indexOf('belastingdienst.nl')!=-1){			// 257787,  enabling an alternate stylesheet while it is still loading is ignored
		opera.defineMagicFunction( 'SwitchStyleSheet', function( fn, th ){
			var args=arguments.slice(2);
			document.addEventListener('load', function(){ fn.apply(th, args ); }, false );
		});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( enabling an alternate stylesheet while it is still loading is ignored). See browser.js for details');
	} else if(hostname.indexOf('bioware.com')>-1){			// 239590, bioware.com uses outdated HierMenus
		fixHierMenus();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (bioware.com uses outdated HierMenus). See browser.js for details');
	} else if(hostname.indexOf('blogger.com')>-1){			// 177059, Blogger: browser detection prevents WYSIWYG editing
		navigator.product = 'Gecko';
		navigator.userAgent = navigator.userAgent.replace(/Opera/, 'Firefox')+' ( rv:1.9.0.3)';
		
		opera.defineMagicVariable(
			'Detect',
			function( obj ){return obj;},
			function( obj ){
				obj.OPERA = function(){return false;}
				obj.MOZILLA = function(){return true;}
				obj.IE=function(){return false;}
				obj.IE_5_5_newer=function(){return false;}
				return obj;
			}
		);
		
				// 187226, Blogger: Should distinguish AltGr and Ctrl
		opera.defineMagicFunction('isCtrlKeyPressed', function(f, t, e){ return e.ctrlKey&&!e.altKey;  });
		opera.defineMagicVariable( 'IE_KEYSET', function(){ return true; },null );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Blogger: browser detection prevents WYSIWYG editing\nBlogger: Should distinguish AltGr and Ctrl). See browser.js for details');
	} else if(hostname.indexOf('bnz.co.nz')>-1){			// 142015, bnz.co.nz use getYear when they should use getFullYear
		Date.prototype.getYear = Date.prototype.getFullYear;
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (bnz.co.nz use getYear when they should use getFullYear). See browser.js for details');
	} else if(hostname.indexOf('britannica.com')>-1){			// 332948, Prevent overwriting document with stats graphic on britannica.com
		avoidDocumentWriteAbuse();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Prevent overwriting document with stats graphic on britannica.com). See browser.js for details');
	} else if(hostname.indexOf('britishairways.')!=-1){			// 206810, Prevent britishairways.com from reloading the page on resize
		opera.defineMagicFunction('resizeHandler', function(){});
				// 256172, britishairways.com hides calendar behind IFRAME
		opera.defineMagicFunction('CP_getCalendar', function(oReal, oThis){
		var cal = oReal.apply(oThis, arguments.slice(2));
		end = cal.indexOf('</iframe>')+9;
		cal = cal.substring(end); 
		return cal; 
		}
		); 
		
				// 269710, Makes calendar work in spite of unexpected order of mouse events
		opera.defineMagicFunction('PopupWindow_hidePopupWindows', function(f,t,e){
			if(e&&e.type=='mouseup'&&e.target&&e.target.tagName=='INPUT'){ return; }
			setTimeout( function(){ f.call(t); }, 500 );
		});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Prevent britishairways.com from reloading the page on resize\nbritishairways.com hides calendar behi...). See browser.js for details');
	} else if(hostname.indexOf('budget.com')>-1){			// 171573, Budget.com: menu appears behind IFRAME "shim"
		document.addEventListener('load', function(){var elm, parent; elm=document.getElementById('DivShim');if(elm){  parent = elm.parentNode; parent.removeChild(elm);parent.appendChild(  document.createElement(  'div'  )  ).id='DivShim';  }  }, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Budget.com: menu appears behind IFRAME "shim"). See browser.js for details');
	} else if(hostname.indexOf('capitalone.com')>-1&&location.protocol=='https:'){			// 86032, CapitalOne login fails - cross-domain access on https disallows setting location
		document.domain='capitalone.com';
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (CapitalOne login fails - cross-domain access on https disallows setting location). See browser.js for details');
	} else if(hostname.indexOf('cdec-sic.cl')!=-1){			// 365516, Old HierMenus on cdec-sic.cl
		fixHierMenus();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Old HierMenus on cdec-sic.cl). See browser.js for details');
	} else if(hostname.indexOf('chase.com')!=-1){			// 243036, chase.com field refocus from onkeypress-problem
		opera.defineMagicFunction('handleTabs', function(oT, oF, name){
			var el=document.getElementById(name);
			if(el && el.value.length+1>=el.maxLength && !(event.keyCode==8||event.keyCode==46)){
				setTimeout( function(){ jumpToNext(el); }, 100);
			}
			function jumpToNext(el){
				var i=0;
				if(el.form){while(el!=el.form[i])i++;}else{ return;}
				if(el.form[i+1])el.form[i+1].focus();
			}
		});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (chase.com field refocus from onkeypress-problem). See browser.js for details');
	} else if(hostname.indexOf('cheaptickets.com')>-1){			// 222065, Cheaptickets new Function() issue workaround
		(function(){
		  var Function = window.Function;
		  window.Function = function(str){
		    return Function.call(this,str.replace(/function\s*\(/g,'function anonymous('));
		  }
		})();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Cheaptickets new Function() issue workaround). See browser.js for details');
	} else if(hostname.indexOf('chosun.com')>-1){			// 279130, Morningplus.chosun.com misplaced content
		addCssToDocument('#scroll_image{ position: relative }');
				// 209929, chosun.com scrollarea fix
		addCssToDocument('#nscrollarea, #nscrolltxt{display: inline !important}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Morningplus.chosun.com misplaced content\nchosun.com scrollarea fix). See browser.js for details');
	} else if(hostname.indexOf('continental.com')>-1){			// 263594, Continental.com document.activeElement fix enables airport choice popup
		opera.addEventListener('BeforeEventListener.click', function(e){if(e.event.target && e.event.target.tagName=='A')document.activeElement=e.event.target; }, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Continental.com document.activeElement fix enables airport choice popup). See browser.js for details');
	} else if(hostname.indexOf('dancenter.com')>-1){			// 166698, Dancenter use getYear when they should use getFullYear
		Date.prototype.getYear = Date.prototype.getFullYear;
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Dancenter use getYear when they should use getFullYear). See browser.js for details');
	} else if(hostname.indexOf('deviantart.com')>-1){			// 282065,  deviantart.com prevents mousedown on file inputs, making it impossible to select files
		opera.addEventListener('BeforeEventListener.mousedown', function(e){
		func_toString.call=preventDefault.call=call;
				if( func_toString.call(e.listener)=='function(){return false}' && e.event.target.tagName=='INPUT' ){
					preventDefault.call(e);
				}
			}, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( deviantart.com prevents mousedown on file inputs, making it impossible to select files). See browser.js for details');
	} else if(hostname.indexOf('douane.nl')!=-1){			// 257787,  enabling an alternate stylesheet while it is still loading is ignored
		opera.defineMagicFunction( 'SwitchStyleSheet', function( fn, th ){
			var args=arguments.slice(2);
			document.addEventListener('load', function(){ fn.apply(th, args ); }, false );
		});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( enabling an alternate stylesheet while it is still loading is ignored). See browser.js for details');
	} else if(hostname.indexOf('fedex.com')!=-1){			// 363564, FedEx.com mangles tables by turning TDs into block elements
		document.addEventListener('DOMContentLoaded', function(){ for(var els=document.getElementsByTagName('td'),el,i=0;el=els[i];i++)if(el.style.display=='block')el.style.display='';}, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (FedEx.com mangles tables by turning TDs into block elements). See browser.js for details');
	} else if(hostname.indexOf('fotocenter.aol.de')>-1){			// 202045, AOL: browser warnings for various features of aol.de
		document.cookie='NewportUnsupportedBrowserAccepted=true;';
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (AOL: browser warnings for various features of aol.de). See browser.js for details');
	} else if(hostname.indexOf('gallery.live.com')>-1){			// 262961, Live.com properties overwrite page from click tracking script
		opera.defineMagicFunction( 'RegisterOmnitureAction', function(){} );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Live.com properties overwrite page from click tracking script). See browser.js for details');
	} else if(hostname.indexOf('geoaccess.com')!=-1){			// 318050,  BlueCross browser sniffing prevents insurance search
		opera.defineMagicVariable('is_nav', function(){return true;}, null);
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( BlueCross browser sniffing prevents insurance search). See browser.js for details');
	} else if(hostname.indexOf('icicidirect.com')>-1){			// 204803, styling INPUT with text-transform can confuse users
		addCssToDocument('input{text-transform: none !important}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (styling INPUT with text-transform can confuse users). See browser.js for details');
	} else if(hostname.indexOf('iieye.com')!= -1){			// 361535, IE detection prevents other browsers from accessing iieye.com
		opera.defineMagicVariable('isIE',function(){return true;}, null);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (IE detection prevents other browsers from accessing iieye.com). See browser.js for details');
	} else if(hostname.indexOf('ingdirect.com.au')>-1){			// 259040, ING Direct login issues
		opera.addEventListener( 'AfterEvent.click',
		function(e){match.call=preventDefault.call=call; if(e.event.target && match.call(e.event.target.id, /^objKeypad/))preventDefault.call(e.event); },
		false );
		
		HTMLInputElement.prototype.getAttribute=(function(ga){
			return function(n){ 
				if( n=='Required'){ 
					return ga.call(this,n)=='Required' ? 'true':'false';
				}; 
				return ga.call(this, n);
			}
		})(HTMLInputElement.prototype.getAttribute);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (ING Direct login issues). See browser.js for details');
	} else if(hostname.indexOf('isbank.com.tr')>-1){			// 265077,  fixing navigation menu on isbank.com.tr
		opera.addEventListener('BeforeScript', function(e){ replace.call=call; e.element.text=replace.call(e.element.text, 'SaklaGoster(sFrameAdi, 0, i.sMenuAd);};else if', 'SaklaGoster(sFrameAdi, 0, i.sMenuAd);}else if') },false);
		
				// 265077, Preventing CSS filter errors on isbank.com.tr
		document.all=undefined;
				// 265077, fixing keypress handler on isbank.com.tr
		var ignoreKeypressCodes = {8:'',9:'',16:'',17:'',35:'',36:'',37:'',38:'',39:'', 40:'',45:'',46:''};
		opera.addEventListener('BeforeEventListener.keypress', function( e ){ preventDefault.call=call; if( e.event.keyCode in ignoreKeypressCodes) preventDefault.call(e); }, false)
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( fixing navigation menu on isbank.com.tr\nPreventing CSS filter errors on isbank.com.tr\nfixing keyp...). See browser.js for details');
	} else if(hostname.indexOf('klm.com')>-1){			// 213449, KLM uses Gecko-specific originalTarget
		addPreprocessHandler( /if \(e\) if \(e\.originalTarget\./g, 'if (e && e.originalTarget) if (e.originalTarget.' );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (KLM uses Gecko-specific originalTarget). See browser.js for details');
	} else if(hostname.indexOf('kr.msn.com')!=-1){			// 349584, head layout broken on kr.msn.com
		addCssToDocument('li:after, ul:after{display:none!important}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (head layout broken on kr.msn.com). See browser.js for details');
	} else if(hostname.indexOf('mail.163.com')!= -1){			// 347923, Fixed add files issue in mail.163.com
		addCssToDocument('.upload .input_browser { width:auto !important}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fixed add files issue in mail.163.com). See browser.js for details');
	} else if(hostname.indexOf('mail.google.')>-1){			// 244011, GMail deletes messages on End key presses
		opera.addEventListener( 'BeforeEventListener.keypress', function(e){
			preventDefault.call=call;
			if(e.event.keyCode==35){
				preventDefault.call(e);
			}
		}, false );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (GMail deletes messages on End key presses). See browser.js for details');
	} else if(hostname.indexOf('makemytrip.com')>-1){			// 206463, MakeMyTrip search fails
		addPreprocessHandler(  /if(document.all)\s*{\s*PassVar(DepDate, RetDate, FromCity, ToCity);/,  '	  if(false){   PassVar(DepDate, RetDate, FromCity, ToCity);' );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (MakeMyTrip search fails). See browser.js for details');
	} else if(hostname.indexOf('mapquest.com')>-1){			// 240094, MapQuest uses .all collection with text nodes in
		opera.addEventListener('BeforeEvent.load', function(e){ 
		    if(document.body){
		        removeEventListener.call=call;
		        document.body.all=null;
		        removeEventListener.call(opera,'BeforeEvent.load', arguments.callee, false);
		    } 
		}, false)
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (MapQuest uses .all collection with text nodes in). See browser.js for details');
	} else if(hostname.indexOf('maps.google.')>-1){			// CORE-17333, The constructor property of DOM nodes should not be Object
		Element.prototype.constructor=Element;
				// CORE-17460, Constructor property of event should be Event interface
		Event.prototype.constructor=Event;
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (The constructor property of DOM nodes should not be Object\nConstructor property of event should be ...). See browser.js for details');
	} else if(hostname.indexOf('maps.live.com')!=-1){			// 165310, Fake oncontextmenu support
		fakeOncontextmenu(true,false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fake oncontextmenu support). See browser.js for details');
	} else if(hostname.indexOf('maps.ubiest.com')>-1){			// 256721, Ubiest.com uses CSS filters if document.all exists
		document.all=null;
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Ubiest.com uses CSS filters if document.all exists). See browser.js for details');
	} else if(hostname.indexOf('millenet.pl')!=-1){			// PATCH-7, Semicolon insertion fails after do..while() conditional
		addPreprocessHandler(/;do num=Math\.ceil\(Math\.random\(\)\*maxNum\);while\(uniqueInt\.a\.hasMember\(num\)\)uniqueInt\.a\[uniqueInt\.a\.length\]=num;/, 'do num=Math.ceil(Math.random()*maxNum);while(uniqueInt.a.hasMember(num));uniqueInt.a[uniqueInt.a.length]=num;');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Semicolon insertion fails after do..while() conditional). See browser.js for details');
	} else if(hostname.indexOf('moneta.co.kr')!=-1){			// 219041,  moneta.co.kr relies on IE quirks for CSS positioning
		addCssToDocument('#stocking{position:relative}#stocking>div{position:absolute}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( moneta.co.kr relies on IE quirks for CSS positioning). See browser.js for details');
	} else if(hostname.indexOf('msnbc.com')>-1){			// 207178, MSNBC sniffing hides Flash content
		opera.defineMagicVariable('oSniff', function(o){return o;},function(){ window['oSniff'].nn=5; });
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (MSNBC sniffing hides Flash content). See browser.js for details');
	} else if(hostname.indexOf('music.mu-mo.net')>-1){			// 256041, mu-mo.net uses SCRIPT for..event.. syntax
		scriptForEventFix();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (mu-mo.net uses SCRIPT for..event.. syntax). See browser.js for details');
	} else if(hostname.indexOf('n-gage.com') >-1 && navigator.userAgent.indexOf('Mac')>-1){			// 181451, N-Gage plugin sniffing does not give Flash to Mac Opera
		opera.defineMagicVariable('g_plugin', function(){return navigator.mimeTypes['application/x-shockwave-flash'].enabledPlugin},null);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (N-Gage plugin sniffing does not give Flash to Mac Opera). See browser.js for details');
	} else if(hostname.indexOf('namooya.com')>-1){			// 241286, Namooya.com main flash does not appear
		document.attachEvent=undefined;
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Namooya.com main flash does not appear). See browser.js for details');
	} else if(hostname.indexOf('nbc4.tv')>-1){			// 215526, NBC4.tv uses capturing load events
		preventEventCapture(window, 'load');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (NBC4.tv uses capturing load events). See browser.js for details');
	} else if(hostname.indexOf('nbcolympics.com')>-1){			// 197145, NBC Olympics site uses capturing load events
		preventEventCapture(window, 'load');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (NBC Olympics site uses capturing load events). See browser.js for details');
	} else if(hostname.indexOf('nectar.com')>-1){			// 240950, Nectar uses getYear where they should use getFullYear
		Date.prototype.getYear=Date.prototype.getFullYear;
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Nectar uses getYear where they should use getFullYear). See browser.js for details');
	} else if(hostname.indexOf('news.msn.co.kr') >-1){			// 342895, news.msn.co.kr navigation bar is offset from the page
		addCssToDocument('#home{position:relative!important}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (news.msn.co.kr navigation bar is offset from the page). See browser.js for details');
	} else if(hostname.indexOf('nick.com')>-1||hostname.indexOf('nickjr.com')>-1){			// 82209, Nick.com flash detection fix
		document.all=null;
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Nick.com flash detection fix). See browser.js for details');
	} else if(hostname.indexOf('nrg.co.il')>-1){			// 244416,  NRG.co.il saving articles does not work
		addPreprocessHandler('document.getElementById("launcher").innerHTML="";', '');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( NRG.co.il saving articles does not work). See browser.js for details');
	} else if(hostname.indexOf('orbitz.com')>-1){			// 240577, Orbitz new Function() issue workaround
		(function(){
		  var Function = window.Function;
		  window.Function = function(str){
		    return Function.call(this,str.replace(/function\s*\(/g,'function anonymous('));
		  }
		})();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Orbitz new Function() issue workaround). See browser.js for details');
	} else if(hostname.indexOf('picasaweb.google')!=-1){			// 304172, Picasaweb browser sniffing removes functionality Opera has no problems with, for example slideshow
		var oldua=navigator.userAgent;
		navigator.userAgent = {
			toString: function(){return oldua},
			toLowerCase:function(){ return oldua.replace( /Opera./, 'MSIE ' ).toLowerCase(); },
			toUpperCase:function(){ return oldua.toUpperCase(); },
			indexOf: function(s){ return oldua.indexOf(s); }
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Picasaweb browser sniffing removes functionality Opera has no problems with, for example slideshow). See browser.js for details');
	} else if(hostname.indexOf('pogo.com')>-1){			// 305697,  Java detection fails on pogo.com
		if(navigator.javaEnabled()){
			var javaVersion = java.lang.System.getProperty('java.version');
			navigator.userAgent += ' Firefox';
			javaVersion=(javaVersion+'').split( '.' ).splice(0,2).join('.');
			navigator.mimeTypes[navigator.mimeTypes.length] = {type: 'application/x-java-applet;version=' + javaVersion };
			navigator.mimeTypes.length = navigator.mimeTypes.length+1;
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( Java detection fails on pogo.com). See browser.js for details');
	} else if(hostname.indexOf('prisjakt.nu')>-1){			// 242474,  prisjakt.nu capturing load events on back navigation
		preventEventCapture(window, 'load');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( prisjakt.nu capturing load events on back navigation). See browser.js for details');
	} else if(hostname.indexOf('rabobank.nl')!=-1){			// 277063,  Rabobank cancels t keypress
		opera.addEventListener('AfterEvent.keypress', function(e){
			preventDefault.call=call;
			if(e.event.keyCode==116 && e.eventCancelled)preventDefault.call(e);
		},false);
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( Rabobank cancels t keypress). See browser.js for details');
	} else if(hostname.indexOf('reviews.cnet.com') >-1){			// 179484, CNet videos: document.write adds a script that depends on variables defined later
		opera.addEventListener('BeforeScript',
		function(ev){ 
				indexOf.call=replace.call=call;
				var js=ev.element.text, problemstr='document.write(\'<script type="text/javascript" src="\'+skin+\'"></script>\');';
				if(indexOf.call(js, problemstr ) > -1 ){
					ev.element.text = replace.call(ev.element.text,  problemstr,'' )+';\n'+problemstr;
			}
		}
		,false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (CNet videos: document.write adds a script that depends on variables defined later). See browser.js for details');
	} else if(hostname.indexOf('sfile.ydy.com')!= -1){			// 361539, Avoid manipulating broken Discuz! markup on sfile.ydy.com
		opera.defineMagicFunction('announcementScroll', function(){});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Avoid manipulating broken Discuz! markup on sfile.ydy.com). See browser.js for details');
	} else if(hostname.indexOf('show.co.kr')!=-1){			// 348818, Pre-filled text as INPUT background not cleared on focus
		document.addEventListener('focus', function(e){if(e.target.tagName=='INPUT'){e.target.style.backgroundImage='none'; e.target.onfocus=null;}},true);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Pre-filled text as INPUT background not cleared on focus). See browser.js for details');
	} else if(hostname.indexOf('siren24.com')!=-1){			// SEOUL-609, ActiveX installation page redirect on siren24.com due to sniffing limitation on redirect script
		navigator.appName = 'Netscape';
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (ActiveX installation page redirect on siren24.com due to sniffing limitation on redirect script). See browser.js for details');
	} else if(hostname.indexOf('sytadin.fr')!=-1){			// 365351, Sytadin.fr IFRAME resize script detects Opera
		fixIFrameSSIscriptII('resizeIframeOnContent');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Sytadin.fr IFRAME resize script detects Opera). See browser.js for details');
	} else if(hostname.indexOf('tdwaterhouse.ca')>-1&&location.protocol=='https:'){			// 147840, tdwaterhouse.ca login fails - cross-domain access on https disallows setting location
		document.domain='tdwaterhouse.ca';
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (tdwaterhouse.ca login fails - cross-domain access on https disallows setting location). See browser.js for details');
	} else if(hostname.indexOf('teletekst.nos.nl')>-1){			// 126136, Teletext focus fix
		window.focus = function () {event.preventDefault();};
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Teletext focus fix). See browser.js for details');
	} else if(hostname.indexOf('tiscali.it')!=-1){			// 344935, Allows some frame nesting on web.tiscali.it
		opera.defineMagicVariable('address', function(current) {
		if (window == window.top && current == window.location) {
		    return (current.search) ? current.href + '&' : current.href+'?';
		}
		return current;
		}, null);
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Allows some frame nesting on web.tiscali.it). See browser.js for details');
	} else if(hostname.indexOf('tistory.com')!=-1){			// 347990, two login buttons on tistory.com
		addCssToDocument('#memberbox .btn-login {text-indent:-100px;}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (two login buttons on tistory.com). See browser.js for details');
	} else if(hostname.indexOf('toeslagen.nl')!=-1){			// 257787,  enabling an alternate stylesheet while it is still loading is ignored
		opera.defineMagicFunction( 'SwitchStyleSheet', function( fn, th ){
			var args=arguments.slice(2);
			document.addEventListener('load', function(){ fn.apply(th, args ); }, false );
		});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( enabling an alternate stylesheet while it is still loading is ignored). See browser.js for details');
	} else if(hostname.indexOf('tuenti.com')!=-1){			// DSK-243723, Problems submitting messages and comments on tuenti.com
		opera.addEventListener('BeforeEventListener.load', function(e){preventDefault.call=call;
			if( e.event.target.contentWindow && e.event.target.contentWindow.location.href =='about:blank' )preventDefault.call(e);
		}, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Problems submitting messages and comments on tuenti.com). See browser.js for details');
	} else if(hostname.indexOf('united.com')>-1 || hostname.indexOf('flyted.com')>-1 || hostname.indexOf('itn.net')>-1){			// 193907,  United.com flight search problem: hidden images do not load, so no onload event
				document.addEventListener('load', function(){
					var i,img;
					var isHidden = function(el){
						if(!el){ return false;}
						var elmIsHidden=((el.style && el.style.display=='none') || window.getComputedStyle(el).display=='none');
						return (elmIsHidden || isHidden( el.parentNode ));
					}
					for(i=document.images.length-1;img=document.images[i];i--){
						if(img.onload){
							if( isHidden( img ) ){
								img.onload();
								return;
							}
						}
					}
				}, false);	
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( United.com flight search problem: hidden images do not load, so no onload event). See browser.js for details');
	} else if(hostname.indexOf('video.nbc.com')>-1||href.indexOf('nbc.com/Video')>-1){			// 243428, NBC.com video problems
		document['all']=null;
		addCssToDocument('#flashcontent{height:550px!important}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (NBC.com video problems). See browser.js for details');
	} else if(hostname.indexOf('wachovia.com')>-1){			// 128405, Viewing checks calls createElement with markup strings if document.all exists
		document.all=null;
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Viewing checks calls createElement with markup strings if document.all exists). See browser.js for details');
	} else if(hostname.indexOf('westjet.com')>-1 ){			// 270752,  Westjet browser sniffing causes reload loop
		opera.defineMagicVariable('browser', function(o){ o.isSupported=true; return o; }, null);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( Westjet browser sniffing causes reload loop). See browser.js for details');
	} else if(hostname.indexOf('worldofwarcraft.com')>-1){			// 237552, Mouseover popups do not appear due to document.all sniffing
		document.all=null;
		fakeOncontextmenu(true, 500);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Mouseover popups do not appear due to document.all sniffing). See browser.js for details');
	} else if(hostname.indexOf('yellowpages.com.au')>-1 ){			// 231853, Yellow pages event capture fix
		preventEventCapture(window, 'load');
			
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Yellow pages event capture fix). See browser.js for details');
	} else if(hostname.indexOf('zdnet.com.com')>-1 ){			// 146580, ZDnet video site plays non-existing files if browser is Opera
		navigator.userAgent=navigator.userAgent.replace(/Opera/, 'MSIE 6.0');	
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (ZDnet video site plays non-existing files if browser is Opera). See browser.js for details');
	} else if(href=='https://www.bookryanair.com/skylights/cgi-bin/skylights.cgi'){			// 182268, Selects are reset if an option is changed from onchange. 
				document.addEventListener('load', function(){
					var selects=document.getElementsByTagName('select'),i,n;
					for(i=0;n=selects[i];i++){
						if(n.name=='country' && n.onchange.toString().indexOf('this.options[(this.length - 1)].value = "other";')>-1 ){
							n.onchange=function(){}
							opera.postError('Opera has modified the JavaScript on '+hostname+' (Ryanair fix). See browser.js for details');
						}
					}
				}, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Selects are reset if an option is changed from onchange. ). See browser.js for details');
	} else if(pathname.indexOf('wp-admin')>-1){			// 261699, Wordpress Admin prev/next link styling makes them unclickable
		addCssToDocument('.navigation{display:inline !important;} .navigation div{display:block !important;}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Wordpress Admin prev/next link styling makes them unclickable). See browser.js for details');
	}
})(opera);
